### ISSUE TITLE
error when start docker-compose up on Mac m1

### ISSUE THREAD

**Issue by KaymeKaydex** [onlineconf/onlineconf#27]
=> ERROR [stage-1 6/6] RUN npm run build                                                                                                                              2.1s
------
 > [stage-1 6/6] RUN npm run build:
#23 1.271 
#23 1.271 > build
#23 1.271 > react-scripts build
#23 1.271 
#23 2.091 node:internal/modules/cjs/loader:499
#23 2.091       throw e;
#23 2.091       ^
#23 2.091 
#23 2.091 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /usr/src/onlineconf-admin/node_modules/postcss-safe-parser/node_modules/postcss/package.json
#23 2.091     at new NodeError (node:internal/errors:387:5)
#23 2.091     at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
#23 2.091     at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
#23 2.091     at resolveExports (node:internal/modules/cjs/loader:493:36)
#23 2.091     at Module._findPath (node:internal/modules/cjs/loader:533:31)
#23 2.091     at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
#23 2.091     at Module._load (node:internal/modules/cjs/loader:804:27)
#23 2.091     at Module.require (node:internal/modules/cjs/loader:1022:19)
#23 2.091     at require (node:internal/modules/cjs/helpers:102:18)
#23 2.091     at Object.<anonymous> (/usr/src/onlineconf-admin/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
#23 2.091   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
#23 2.091 }
#23 2.091 
#23 2.091 Node.js v18.6.0
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
ERROR: Service 'onlineconf-admin' failed to build : Build failed

**Comment by Nikolo** [comment]
Same problem but not M1.
WSL Ubuntu 22.04.1 LTS

**Comment by KaymeKaydex** [comment]
#28

**Comment by KaymeKaydex** [comment]
now fix was merged
